name: simulation
root: ./
startup_window: status
pre_window: export USV_NAME=wamv;
windows:
  - pkill:
      layout: tiled
      panes:
        - history -s pkill tmux
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch offshore_uav_pack offshore_rig.launch
  - spawn_wamv:
      layout: tiled
      panes:
        - export USV_NAME=wamv; waitForSimulation; roslaunch offshore_uav_pack wamv.launch
  - controlWAMV:
      layout: tiled
      panes:
        - export USV_NAME=wamv; history -s  roslaunch offshore_uav_pack wamv_usv.launch
  # - GPS:
      # layout: tiled
      # panes:
        # - history -s rostopic echo /wamv/sensors/gps/gps/fix
  # - IMU:
      # layout: tiled
      # panes:
        # - history -s rostopic echo /wamv/sensors/imu/imu/data